### ISSUE TITLE
White space is required before markdown code.

### ISSUE THREAD

**Issue by at-wat** [gbiggs/ros_moveit_rsj_tutorial#3]
Several markdown codes have not been processed correctly.
e.g. https://github.com/gbiggs/ros_moveit_rsj_tutorial/blame/gh-pages/ros_basics.md#L219

- **Invalid** 「に__Ctrl+C__」
- **Invalid** 「a__Ctrl+C__」
- **Valid** 「に __Ctrl+C__」
- **Valid** 「に(__Ctrl+C__)」

**Comment by at-wat** [comment]
- **Valid** 「に、__Ctrl+C__」
- **Valid** 「に　__Ctrl+C__」
- **Valid** 「。__Ctrl+C__」
- **Valid** 「（__Ctrl+C__」
- **Invalid** 「に、__Ctrl+C__を」

**Comment by gbiggs** [comment]
Closed by cc13cda6720fcb34b197cb028147901242ec97f3
